sudo: required

language: cpp

addons:
    apt:
        packages:
            - libgmp-dev
            - libmpfr-dev

before_install:
    - sudo apt-get -qq update
    - sudo apt-get install libmpfi-dev libboost1.48-all-dev
    
before_script:
    - cp config.cmake.example config.cmake
    - mkdir build
    - cd build
    - cmake ..
    
script: make            